version: '2'
networks:
  proxy-tier:
    external:
      name: nginxproxy_proxy-tier

services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

  odoo11:
    image: odoo:11.0
    depends_on:
      - db
    ports:
      - "8083:8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    environment:
      - VIRTUAL_PORT=8069
#     - HTTPS_METHOD=nohttps
      - VIRTUAL_HOST=zikovauto.dravom.cz
      - LETSENCRYPT_HOST=zikovauto.dravom.cz
      - LETSENCRYPT_EMAIL=milda.dvorak@gmail.com
    volumes:
      - ./o_addons:/mnt/extra-addons
      - ./o_etc:/etc/odoo
    networks:
      - proxy-tier
      - default

volumes:
  db:
  odoo11:
